ALTER TABLE events ADD COLUMN image_path TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN banner_path TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN latitude REAL;
ALTER TABLE events ADD COLUMN longitude REAL;
